<script> var hostUrl = "/";</script>
<script src="{{ asset('assets/plugins/global/plugins.bundle.js') }}"></script>
<script src="{{ asset('assets/plugins/custom/prismjs/prismjs.bundle.js') }}"></script>
<script src="{{ asset('assets/cms_js/scripts.bundle.js') }}"></script>
<script src="{{ asset('assets/plugins/custom/datatables/datatables.bundle.js') }}"></script>
<script src="{{ asset('assets/plugins/custom/fullcalendar/fullcalendar.bundle.js') }}"></script>
<script src="{{ asset('assets/plugins/custom/formrepeater/formrepeater.bundle.js') }}"></script>
<script src="{{ asset('assets/cms_js/index.js') }}"></script>
<script src="{{ asset('assets/cms_js/xy.js') }}"></script>
<script src="{{ asset('assets/cms_js/percent.js') }}"></script>
<script src="{{ asset('assets/cms_js/radar.js') }}"></script>
<!-- <script src="{{ asset('assets/js/themes/Animated.js') }}"></script> -->
<script src="{{ asset('assets/cms_js/map.js') }}"></script>
<script src="{{ asset('assets/cms_js/worldLow.js') }}"></script>
<script src="{{ asset('assets/cms_js/continentsLow.js') }}"></script>
<script src="{{ asset('assets/cms_js/usaLow.js') }}"></script>
<script src="{{ asset('assets/cms_js/worldTimeZonesLow.js') }}"></script>
<script src="{{ asset('assets/cms_js/worldTimeZoneAreasLow.js') }}"></script>
<script src="{{ asset('assets/cms_js/widgets.bundle.js') }}"></script>
<script src="{{ asset('assets/cms_js/custom/utilities/modals/new-target.js') }}"></script>
<script src="{{ asset('assets/cms_js/custom/utilities/modals/users-search.js') }}"></script>
<script src="{{ asset('assets/cms_js/summernote_0.8.2_summernote.js') }}"></script>
<script src="{{ asset('public/form-js/file-getmime-image.js') }}"></script>
<script src="{{ asset('public/form-js/file-getmime-pdf.js') }}"></script>
@stack('post-scripts')